# =============================================================================
#  scripts/vmt_exposure_model.R
#  VMT-BASED EXPOSURE MODEL — replaces the vehicle-count formulation.
#
#  Why this exists
#  ---------------
#  Emissions are a function of distance travelled, not of how many vehicles are
#  registered. The old chain was
#      fleet count -> adoption fraction -> modelled corridor flows -> emissions
#  with the flows generated by the CTM and never checked against anything.
#  The Massachusetts Vehicle Census publishes OBSERVED annual VMT for every
#  Boston ZIP, so the chain becomes
#      observed ZIP VMT x fleet mix(t) x emission factor(t) -> emissions
#  which removes C_0, A_0 and the fleet-turnover machinery from the critical
#  path and replaces a modelled quantity with a measured one.
#
#  Three fleet classes, not two: conventional / hybrid / zero-emission.
#  9.6% of Boston VMT is hybrid and the binary model could not represent it.
# =============================================================================

source(if (file.exists("config/params.R")) "config/params.R" else "../config/params.R")
D <- derive_params()
v <- function(x) x$value

# ---- emission factors, per class, per year ----------------------------------
# ICE and BEV interpolate between the two MOVES years; hybrid is constructed as
# a fixed fraction of the contemporaneous ICE rate so it improves alongside it.
horizon   <- v(SSM$horizon)
yrs       <- 0:horizon
ef_ice    <- D$ef_ice_t
ef_bev    <- D$ef_av_t
hyb_ratio <- (v(EF$hybrid$exhaust) + v(EF$hybrid$brake) + v(EF$hybrid$tire)) / D$ef_ice
ef_hyb    <- ef_ice * hyb_ratio

# ---- observed ZIP-level VMT -------------------------------------------------
zf <- if (file.exists("outputs/mvc_zip_vmt.csv")) "outputs/mvc_zip_vmt.csv" else "../outputs/mvc_zip_vmt.csv"
zip <- read.csv(zf, stringsAsFactors = FALSE, colClasses = c(ZIPCODE = "character"))
zip <- zip[zip$modelled %in% c(TRUE, "TRUE"), ]

# The manuscript says "28 ZIP codes (02108-02136, 02199, 02203, 02210, 02215)".
# That enumeration is actually 33 ZIPs. The discrepancy resolves once the five
# PO-box / non-residential ZIPs are dropped - 02112, 02117, 02123, 02133 and
# 02203 carry negligible VMT (each under 1M mi/yr against a city total of 3.1e9).
# So "28" is correct and the enumerated list in the paper is what is wrong.
PO_BOX <- c("02112", "02117", "02123", "02133", "02203")
cat("Dropping PO-box / non-residential ZIPs: ", paste(PO_BOX, collapse = ", "), "\n")
zip <- zip[!zip$ZIPCODE %in% PO_BOX, ]
MI_TO_KM <- 1.609344
zip$vkt <- zip$TOTAL * MI_TO_KM          # vehicle-km per year

cat(sprintf("Modelled ZIPs: %d, observed %.3g vehicle-km/yr\n", nrow(zip), sum(zip$vkt)))

# ---- exogenous VMT growth ---------------------------------------------------
# Observed Boston VMT grew 18.4% over 2020-2025 with no AVs involved (3.4%/yr).
# This is a BASELINE trend. Rebound must be measured against it, not confused
# with it. Damped toward zero over the horizon rather than compounded forever.
vmt_growth_0 <- 0.034
vmt_damping  <- 0.10
growth_path  <- cumprod(c(1, 1 + vmt_growth_0 * exp(-vmt_damping * yrs[-1])))

#' Total PM2.5 emitted per year across the modelled ZIPs.
#' @param share_bev,share_hyb numeric vectors of length horizon+1, VMT shares
#' @param rebound extra VMT induced by automation, as a fraction, applied to
#'        the automated share only
exposure <- function(share_bev, share_hyb, rebound = 0) {
  stopifnot(length(share_bev) == length(yrs), length(share_hyb) == length(yrs))
  share_ice <- pmax(0, 1 - share_bev - share_hyb)
  base_vkt  <- sum(zip$vkt) * growth_path
  # rebound scales the automated (BEV) portion of travel only
  vkt_t     <- base_vkt * (1 + rebound * share_bev)
  ef_fleet  <- share_ice * ef_ice + share_hyb * ef_hyb + share_bev * ef_bev
  list(year = yrs, vkt = vkt_t, ef_fleet = ef_fleet,
       grams = vkt_t * ef_fleet,
       tonnes = vkt_t * ef_fleet / 1e6)
}

#' Per-ZIP emissions in a given year — feeds the dispersion source term.
exposure_by_zip <- function(share_bev, share_hyb, year_index, rebound = 0) {
  i  <- year_index + 1
  sb <- share_bev[i]; sh <- share_hyb[i]
  ef <- (1 - sb - sh) * ef_ice[i] + sh * ef_hyb[i] + sb * ef_bev[i]
  data.frame(ZIPCODE = zip$ZIPCODE,
             vkt     = zip$vkt * growth_path[i] * (1 + rebound * sb),
             ef      = ef,
             grams   = zip$vkt * growth_path[i] * (1 + rebound * sb) * ef)
}

# ---- demonstration against the current scenario set -------------------------
if (sys.nframe() == 0) {
  sc <- read.csv(if (file.exists("StateModel/av_all_scenarios.csv"))
                 "StateModel/av_all_scenarios.csv" else "../StateModel/av_all_scenarios.csv")
  # observed hybrid trajectory, extrapolated flat beyond the data
  hyb_obs <- as.numeric(par_val("SSM","obs_hybrid_share"))
  share_hyb <- c(hyb_obs, rep(tail(hyb_obs,1), length(yrs) - length(hyb_obs)))[seq_along(yrs)]

  cat("\n=== Annual traffic-attributable PM2.5, modelled ZIPs (tonnes/yr) ===\n")
  cat(sprintf("%-18s %10s %10s %10s %12s\n", "scenario", "yr 0", "yr 15", "yr 30", "% change"))
  out <- list()
  for (s in unique(sc$scenario)) {
    sb <- sc$pct_AV[sc$scenario == s]
    if (length(sb) != length(yrs)) next
    e <- exposure(sb, share_hyb, rebound = par_val("REBOUND","high"))
    out[[s]] <- e
    cat(sprintf("%-18s %10.1f %10.1f %10.1f %11.1f%%\n", s,
                e$tonnes[1], e$tonnes[16], e$tonnes[31],
                (e$tonnes[31]/e$tonnes[1]-1)*100))
  }
  saveRDS(out, "outputs/vmt_exposure.rds")
  cat("\nWrote outputs/vmt_exposure.rds\n")
  cat(sprintf("\nBaseline VMT growth assumption: %.1f%%/yr damped at %.2f\n",
              vmt_growth_0*100, vmt_damping))
  cat(sprintf("Rebound applied to automated share: %.0f%%\n", par_val("REBOUND","high")*100))
}
